In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("../data/insurance.csv")

In [4]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
X=df.drop("charges",axis=1)
y=df["charges"]

In [6]:
X.head()

   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [7]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [8]:
X.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
dtype: object

In [10]:
X.shape

(1338, 6)

In [11]:
y.shape

(1338,)

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
categorical_features=['sex','smoker','region']

In [14]:
preprocessor=ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(drop='first'),categorical_features)
    ],
    remainder='passthrough'
)

In [15]:
X_processed=preprocessor.fit_transform(X)

In [16]:
print(type(X_processed))

<class 'numpy.ndarray'>

In [17]:
X_processed.shape

(1338, 8)

In [18]:
feature_names=preprocessor.get_feature_names_out()
print(feature_names)

['cat__sex_male' 'cat__smoker_yes' 'cat__region_northwest'
 'cat__region_southeast' 'cat__region_southwest' 'remainder__age'
 'remainder__bmi' 'remainder__children']

In [19]:
X_processed=pd.DataFrame(
    X_processed,
    columns=feature_names)

In [20]:
X_processed.head()

,cat__sex_male,cat__smoker_yes,cat__region_northwest,cat__region_southeast,cat__region_southwest,remainder__age,remainder__bmi,remainder__children
0,0.0,1.0,0.0,0.0,1.0,19.0,27.900,0.0
1,1.0,0.0,0.0,1.0,0.0,18.0,33.770,1.0
2,1.0,0.0,0.0,1.0,0.0,28.0,33.000,3.0
3,1.0,0.0,1.0,0.0,0.0,33.0,22.705,0.0
4,1.0,0.0,1.0,0.0,0.0,32.0,28.880,0.0

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(
    X_processed,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1070, 8)
(268, 8)
(1070,)
(268,)

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
model=LinearRegression()

In [27]:
model.fit(X_train,y_train)

LinearRegression()

In [29]:
y_pred=model.predict(X_test)

In [31]:
predictions=pd.DataFrame({
    "Actual":y_test,
    "Predicted":y_pred
})
predictions.head(10)

           Actual     Predicted
764    9095.06825   8969.550274
887    5272.17580   7068.747443
890   29330.98315  36858.410912
1293   9301.89355   9454.678501
259   33750.29180  26973.173457
1312   4536.25900  10864.113164
899    2117.33885    170.280841
752   14210.53595  16903.450287
1286   3732.62510   1092.430936
707   10264.44210  11218.343184

In [33]:
from sklearn.metrics import(
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

In [34]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

In [35]:
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE : 4181.19447375367
MSE : 33596915.85136151
RMSE: 5796.284659276277
R² Score: 0.783592976712072